DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include("app01.urls"))
]

DjangoProject/app01/urls.py
from django.urls import path
from app01 import views

urlpatterns = [
    path('add_publisher/', views.add_publisher),
    path('publisher_list/', views.publisher_list)
]

DjangoProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

DjangoProject/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # the 'name' value as called by the {% url %} template tag
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

DjangoProject/app01/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64, null=False)
    address = models.CharField(max_length=64, null=False)

DjangoProject/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

DjangoProject/app01/views.py
from django.shortcuts import render, redirect
from app01 import models

# Create your views here.
def add_publisher(request):
    if request.method == 'POST':
        # 获取表单提交的信息
        publisher_name = request.POST.get("name")
        publisher_address = request.POST.get("address")
        # 保存到数据库
        models.Publisher.objects.create(name=publisher_name, address=publisher_address)
        return redirect('/app01/publisher_list')

    return render(request, "add_publisher.html")

def publisher_list(request):
    return render(request, "publisher_list.html")

DjangoProject/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question

from django.template import loader
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)
    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    # return HttpResponse("Hello, word. You're at the polls index.")

def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
    # return HttpResponse("You're looking at the results of question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % question_id)
"""
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

    # return HttpResponse("You're voting on question %s." % question_id)

DjangoProject/app01/templates/add_publisher.html
{% extends "base.html" %}

{% block bar %}


{% endblock %}

<form action="" method="post">
    {% csrf_token %}
    <p>
        出版社名称 <input type="text" name="name">
    </p>
    <p>
        出版社地址 <input type="text", name="address">
    </p>
    <p>
        <button type="submit" class="btn">提交</button>
    </p>
</form>
</body>
</html>

DjangoProject/app01/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" >
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--上述3个mate标签必须放在最前面，任何其他内容都必须跟随其后！-->
    <title>图书管理系统</title>

    <!--Bootstrap-->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js'%}"></script>

    <!-- HTML5 ship 和Respond.js 是为了让 IE8 支持HTML5元素和媒体查询(media queries)功能 -->
    <!-- 警告：通过 file:// 协议(直接将html页面拖拽到浏览器中) 访问页面时 Respond.js 不起作用 -->
    <!-- [if it IE 9]-->
    <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
    <script src="{% static 'js/respond.min.js'%}"></script>
    <!-- [endif]   -->
</head>
<body>
    <!-- 分页名称 -->
    <h1 class="text-center">图书管理系统</h1>
    <!-- 这是导航栏 -->
    {% include 'nav.html' %}
    <!-- 这是倒栏 -->
    <div class="container-fluid">
        <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-sidebar">
                {% block nav %}

                {% endblock %}
            </ul>
        </div>
        <!-- 标题栏 -->
        {% block bar %}

        {% endblock %}
        <!-- 主程序 -->
        {% block main %}

        {% endblock %}

        <!-- 这是页码 -->
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
</body>
</html>

DjangoProject/app01/templates/nav.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/app01/book_list">首页</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/app01/book_list/">图书列表<span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="/app01/author_list/">作者列表</a></li>
            <li class="active"><a href="/app01/publisher_list/">出版社列表</a></li>
                <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
            </li>
            </ul>
            <form action="" class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="#" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div> <!-- /.navbar-collapse -->
    </div> <!-- /.container-fluid -->
</nav>

DjangoProject/app01/templates/publisher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>
        这是出版社列表页
    </h1>
</body>
</html>

DjangoProject/mysite/polls/templates/polls/detail.html
<form action="{ url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>
                {{ question.question_text }}
            </h1>
        </legend>
        {% if error_message %}<p>
        <strong>
            {{ error_message }}
        </strong>
    </p>
        {% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ for loop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ for loop.counter}}">{{ choice.choice_text }}</label>
        <br> {% end for %}
    </fieldset>
    <input type="submit" value="Vote">
</form>




<!--<h1>-->
<!--     {{ question.question_text }}-->
<!--</h1>-->
<!--<ul>-->
<!--    {% for choice in question.choice_set.all %}-->
<!--        <li>{{ choice.choice_text }}<li>-->
<!--    {% end for %}-->
<!--</ul>-->

DjangoProject/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
        {% end for %}
    </ul>
{% else %}
    <p>
        No polls are available.
    </p>
{% endif %}

DjangoProject/mysite/polls/templates/polls/results.html
<h1>
    {{ question.question_text }}
</h1>
<ul>
    {%  for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
    </li>
    {% end for %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>